### ISSUE TITLE
RCEconomy anstatt Vault verwenden

### ISSUE THREAD

**Issue by Silthus** [raidcraft/rccities#13]
Um den genaueren Geldfluss inkl. Details nachzuvollziehen sollte nach der Fertigstellung von [RCEconomy](https://github.com/raidcraft/economy) der Wrapper von RCEconomy verwendet werden.

Außerdem sollte das Bank Feature von RCEconomy/Vault für das Verwalten des Geldes der Städte verwendet werden. Dadurch kann ein besserer Geldfluss nachvollzogen werden.

*Es dauert noch ein bisschen bis RCEconomy fertig ist, ich sage hier Bescheid und poste Details.*

**Comment by PhilipU** [comment]
Aktuell wird sogar nciht einmal mehr Vault verwendet, da das aktuelle Economy Plugin scheinbar die Vault Schnittstelle nicht richtig bedient und es nicht erlaubt ohne Spieler-Kontext Konten zu verwalten. Ich habe einfach die Stadtkassen Info in die Datenbank mit aufgenommen. Sobald RCEconomy verfügbar ist lässt sich das leicht umbauen.

**Comment by PhilipU** [comment]
Es wird nun RCEconomy verwendet (+ Transfer Details), die City-Accounts werden aber immernoch selbst verwaltet. Das wird als nächstes angepasst.
