### ISSUE TITLE
Pistons können nicht über die Chunkgrenze verwendet werden [BUG]

### ISSUE THREAD

**Issue by PhilipU** [raidcraft/rccities#31]
WG verhindert das nutzen von Pistons über die Chunkgrenze

**Comment by PhilipU** [comment]
Blöcke verschieben geht immernoch nicht

**Comment by Silthus** [comment]
Vielleicht könnte man das auch lösen in dem man für die gesamte Stadt eine Parent Polygon Region anlegt die Parent aller anderen Regionen ist. So könnte man die Flags auch leichter verwalten und hat bei riesigen Städten einen Performance Gewinn.
